
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    #数据源的自动配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac?useUnicode=true&useSSL=false&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 10
      min-idle: 2
      validation-query: select 'x'
      stat-view-servlet:
        login-username: admin
        enabled: true  #启用监控页
        login-password: admin
        allow:
        deny:
        url-pattern: /druid/*
pagehelper:
  helper-dialect: mysql
  reasonable: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


